//
// Created by Felicia Chen on 11/22/22.
//

#ifndef FELICIACHENCS3AFINAL_FONTSENUM_H
#define FELICIACHENCS3AFINAL_FONTSENUM_H

enum fontsEnum
{
    SNOWY_WINTER, ROBOTO, RAINY_HEARTS,

    LAST_FONT
};

#endif //FELICIACHENCS3AFINAL_FONTSENUM_H
